# Config file for build_and_run_idf_examples.yml workflow

# This file contains configuration settings for the idf-build-apps tool,
# which is used to build and run example applications in the workflow.
# If you change the 'build_dir' value, make sure to update the corresponding
# Run step in the workflow, as it will need to reference the new build directory.

paths = [
    "examples/peripherals/usb/device",     # ESP-IDF USB Device examples path
    "examples/network/sta2eth",            # Networking example using USB Device
]

# Exclude cherryusb-based device examples
exclude = [
    "examples/peripherals/usb/device/cherryusb_serial_device",
]

recursive = true
check_warnings = true
target = "all"
enable_preview_targets = true

# Build related options (build_dir uses '@t' for target and '@w' for wildcard pattern (sdkconfig usually)
build_dir = "build_@t_@w"

# config rules
config_rules = [
    'sdkconfig.ci=default',
    'sdkconfig.ci.*=',
    '=default',
]
